server:
  port: 8001
spring:
  application:
    name: springboot1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
springbootribbon:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule